### ISSUE TITLE
Best practices around non-persistent URIs without using blank nodes

### ISSUE THREAD

**Issue by edmondchuc** [ternaustralia/ontology_tern#10]
Avoiding blank nodes simplify queries and downstream applications. When we validate data using SHACL, we produce sub-graphs to avoid loading the entire knowledge graph into memory. Having blank nodes complicates this and makes it very hard to scale as each target class for SHACL validation requires modification to the SPARQL query. 

Our current solution is to replace all uses of blank nodes with a non-persistent URI. All individuals use the base URI just like persistent and named individuals except their local name is prefixed with an underscore (`_`). 

Example: 
```
http://linked.data.gov.au/dataset/ausplots-rangelands/_bc4a8844-cb51-49f6-837b-d5b8f884af6e
......................................................^....................................
```

The nice thing with this is that all individuals in our knowledge graph are now named, therefore we can retrieve data from a SPARQL endpoint at any granularity level as we wish (example use case - using a graph viewer like [Ontodia](https://github.com/metaphacts/ontodia)). The downside to this practice is that we are using a non-standard way of representing unnamed individuals (blank nodes). And if people are unfamiliar with our practice, they may interpret it as a persistent name. 

We need to document this somewhere.

**Comment by dr-shorthair** [comment]
> replace all uses of blank nodes with a non-persistent URI

... which I think is how they are handled internally anyway by all triple/graph stores?

Why not just make these URIs persistent?

**Comment by edmondchuc** [comment]
I think this is no longer relevant as it is an implementation detail.
