### ISSUE TITLE
Should Result only have 1 sosa:isResultOf property or a minimum of 1?

### ISSUE THREAD

**Issue by edmondchuc** [ternaustralia/ontology_tern#109]
In SOSA, an activity (Observation, Actuation or Sampling) expects at least 1 `sosa:isResultOf` relationship. 

Is there any scenarios in the ecological domain where Results are the products of more than one activity?

Related: https://github.com/ternaustralia/ontology_tern/pull/96

**Comment by dr-shorthair** [comment]
In the SHACL/validation step, I'd suggest either 0..1 else 1..1
1..1 does force people to create an act where sometimes it is not important so this may feel like too much burden (though ontologically there is always an act of creation).

**Comment by edmondchuc** [comment]
@dr-shorthair let's reinstate 1..1 for `sosa:isResultOf` on `Result` in the SHACL while keeping the OWL restriction the same as SOSA.

We can always go from 1..1 to 0..1 quite easily, but not so much the other way around.
