### ISSUE TITLE
Update W3ID redirects to point to GH pages instead of https://raw.githack.com/

### ISSUE THREAD

**Issue by edmondchuc** [ternaustralia/ontology_tern#116]
We are currently using https://raw.githack.com/ with their development URLs for serving the Turtle files out of this repository. The development URLs rate limit the number of requests to the server which may become blockers on TERN's side.

We had to use https://raw.githack.com/ because it served the files back with the correct content-type header while GitHub's raw.githubusercontent.com did not (defaults to `text/html`). 

I checked with GitHub Pages just now and it serves the files back with the correct content-type header for Turtle files (`text/turtle`). We need to switch the W3ID redirects from the https://raw.githack.com/ service to GH pages.

**Comment by dr-shorthair** [comment]
When you transition to 'production' you should move to https://rawcdn.githack.com/ - as explained on the https://raw.githack.com/ homepage

**Comment by edmondchuc** [comment]
Unfortunately, the production CDN URLs are cached for a year. Changes to those files will not get updated unless we manually purge them on their website. The purge functionality is also rate limited.

> Requests to CDN are routed through [CloudFlare](http://cloudflare.com/)'s content delivery network, and are cached for a year the first time they're loaded. This results in the best performance and reduces load on raw.githack.com and on underlying service, but it means that reloading won't fetch new changes.

**Comment by edmondchuc** [comment]
Fixed by https://github.com/perma-id/w3id.org/pull/2528.

**Comment by dr-shorthair** [comment]
When did GitHub upgrade? Is it only GitHub pages?

**Comment by edmondchuc** [comment]
> When did GitHub upgrade?

I am not sure. It is entirely possible that GH pages always had the correct content type headers set and we never noticed it.

> Is it only GitHub pages?

Yes, it's only GH pages.

You can test it out with `curl` or any other HTTP client.

---

Request to raw.githubusercontent.com:

```
curl -L https://raw.githubusercontent.com/ternaustralia/ontology_tern/master/docs/tern.ttl -v
```

Response content-type header:

```
< content-type: text/plain; charset=utf-8
```

---

Request to GH pages:

```
curl -L https://ternaustralia.github.io/ontology_tern/tern.ttl -v
```

Response content-type header:

```
< content-type: text/turtle; charset=utf-8
```

**Comment by dr-shorthair** [comment]
I tested with Postman
