### ISSUE TITLE
The value of `tern:Attribute` should not be represented with a `tern:Result`

### ISSUE THREAD

**Issue by edmondchuc** [ternaustralia/ontology_tern#12]
An act of sampling or observation produces a result whereas an attribute of a feature of interest is just a value. Therefore, the value of an Attribute should have a class representative of a value. 

Proposal: create class `tern:Value` and fix up relationships for `tern:Attribute`

Question: how to model the current subclasses of `tern:Result` (`tern:Boolean`, `tern:QuantitativeMeasure`, etc)? They are specialisations of `tern:Value` but they *may* be a `tern:Result`. How to model the *may* part? Do we still need `tern:Result`?

**Comment by smguru** [comment]
it should be tern: ResultType instead of tern: Result; I am not sure why tern: value should be a call, it is just an attribute and value Type can be the same as result type

**Comment by edmondchuc** [comment]
The types of results are modelled as classes to capture additional information such as uncertainty. This is the pattern used in SOSA already. See [sosa:Observation](https://www.w3.org/TR/vocab-ssn/#SOSAObservation). See [tern:Result](https://ternaus.atlassian.net/wiki/spaces/DAWE/pages/2003828759/TERN+Ontology#Result).

SOSA uses the `sosa:hasSimpleResult` property to capture the value as RDF literals (for convenience).

**Comment by edmondchuc** [comment]
The current usage of `tern:Result` with `tern:Observation`, `tern:Attribute` and `tern:Sampling`.

![https://i.imgur.com/1NyBAHK.png](https://i.imgur.com/1NyBAHK.png)

**Comment by dr-shorthair** [comment]
Don't forget `rdfs:Resource` and `owl:Thing`. 

Note that the only distinctive property of a `sosa:Result` is a pointer to the act that generated it - in SOSA this is a union of ( `Observation`, `Sampling`, and `Actuation`). (In TERN Ontology you have only carried over the `sosa:Observation` option.) This is the giveaway really: `Result` is a sub-class of `Thing` that is associated with an act of generation. If that act is of no interest, then use the superclass.

**Comment by edmondchuc** [comment]
Thanks Simon!

The TERN Ontology has `sosa:isResultOf` as a union of `Observation`, `Sampling` and `Attribute`. Looks like TopBraid Composer is not generating the diagram correctly.

I've created the `tern:Value` class as the set of all value-type classes. The target classes for `tern:hasValue` and `sosa:hasResult` for classes `tern:Attribute` and `tern:Observation` have been changed from `tern:Result` to `tern:Value`. 

For `tern:Sampling`, the target class for `sosa:hasResult` remains as `tern:Result`.

![https://i.imgur.com/7T2QCOK.png](https://i.imgur.com/7T2QCOK.png)

This change will be merged into the `develop` branch. @dr-shorthair, let me know if you see any issues before we merge it into `master`.

**Comment by edmondchuc** [comment]
In `develop` by https://github.com/ternaustralia/ontology_tern/pull/19

**Comment by edmondchuc** [comment]
As discussed in today's meeting, we need to do a review to determine if the `tern:Result` class is required. It currently exists purely to align to SOSA/SSN. 

I will do an analysis on the implications of removing `tern:Result` and report back here.

**Comment by edmondchuc** [comment]
`tern:Observation`'s property shape for `sosa:hasResult` now expects a value that is `tern:Value` and a `tern:Result`. See https://github.com/ternaustralia/ontology_tern/pull/55.

**Comment by edmondchuc** [comment]
Since this is no longer an issue in `master`, I am closing it.
