### ISSUE TITLE
sosa:resultTime datatype limitations relative to data

### ISSUE THREAD

**Issue by miekeGR** [ternaustralia/ontology_tern#135]
Data that we have been investigating for the BDR in fields equivalent to dwc:eventDate, dwc:dateIdentified are not as precise to have a recorded time (just date). To fulfil the validation requirements on sosa:resultTime we need xsd:dateTime. Is there a particular default time we should implement to fulfil the requirement or can the datatype options be expanded to reflect the data precision more accurately?

**Comment by dr-shorthair** [comment]
When designing the ontology, we chose `xsd:dateTimeStamp` because union datatypes are underspecified in OWL, so we had to choose just one. I would suggest the TERN Ontology SHACL could quite reasonably relax that to `xsd:date` which is a very common (probably the most common) precision in eco surveys.

**Comment by edmondchuc** [comment]
@dr-shorthair SOSA specifies `sosa:resultTime` with `rdfs:range` as `xsd:dateTime`. See https://prefix.zazuko.com/sosa:resultTime. 

I am not sure if there is any implications with `rdfs:range` if used with an RDFS reasoner. Would the reasoner see an `xsd:date` value and produce an additional literal value as `xsd:dateTime`? @nicholascar do you know?

**Comment by nicholascar** [comment]
Sorry no: no reasoner could go from `xsd:date` to `xsd:dateTime` or `xsd:dateTimeStamp`. 

SPARQL, or at least some triplestores, contains casts the other way around but not in that direction, given the lower to higher precision.

You might have to implement a special TERN property here and it can't be a sub property of `sosa:resultTime` either as that would require the same, or more restrictive, range.

**Comment by edmondchuc** [comment]
@nicholascar thanks.

I think we have a few options here.

1. Create a new property `tern:resultDate` which requires the value to be an `xsd:date`
2. Continue using `sosa:resultTime` but set the time portion to `T00:00:00Z` (midnight UTC)
3. Create a new super property `tern:resultDateTime` which allows for both `xsd:date` and `xsd:dateTime` values.

Thoughts?

**Comment by nicholascar** [comment]
Please don't do # 2.! Always misleading to make up times.

I think 3. - superproperty - is the way to go. Make sure to allow `xsd:dateTimeStamp` for it too!

**Comment by miekeGR** [comment]
I also like option 3. Thanks all.

**Comment by dr-shorthair** [comment]
4. Continue to use `sosa:resultTime` but with a `xsd:date` value

Then submit a CR to W3C to relax the range of `sosa:resultTime`

**Comment by edmondchuc** [comment]
@dr-shorthair - is creating a change request just a matter of creating an issue in https://github.com/w3c/sdw/issues?

I am thinking we should move forward for now with `tern:resultDateTime` until `sosa:resultTime` is changed upstream. The reasoning for this is because systems need to load in SOSA for the validators to work correctly, and loading SOSA will load in the problematic statement `sosa:resultTime rdfs:range xsd:dateTime`. Once W3C agrees and relaxes the range, we can go back to using `sosa:resultTime`.

Does this sound good? @dr-shorthair @nicholascar @miekeGR

**Comment by dr-shorthair** [comment]
Do the validators use the `rdfs:range` constraints from the W3C ontology?

**Comment by edmondchuc** [comment]
Oh yeah, good point @dr-shorthair, I don't think the validators need to import it.

Then are we happy with the continue use of `sosa:resultTime`? 

I can update the property shapes for `sosa:resultTime` to allow for `xsd:date`, `xsd:dateTime` and `xsd:dateTimeStamp`.

**Comment by nicholascar** [comment]
The validators don't directly import it but we do apply SOSA expansion to data during validation and, since we use the strict TopBraid expanders, they might throw errors. So please do implement your option 3. above Edmond and don't just overload `sosa:resultTime`

**Comment by miekeGR** [comment]
@edmondchuc we are still happy to use option 3.

**Comment by miekeGR** [comment]
@edmondchuc should I close this issue now or when you have implemented tern:resultDateTime?

**Comment by dr-shorthair** [comment]
I tend to be guided more by what the queries are going to look like. 
In order to make queries portable, it is best to stick with the standard predicates ...

**Comment by dr-shorthair** [comment]
> don't just overload sosa:resultTime

Like [I said](https://github.com/ternaustralia/ontology_tern/issues/135#issuecomment-1053891376), the reason the SOSA rdfs:range is what it is is because OWL doesn't allow union datatypes. It was not because we thought that precision was always needed. I now think it was a mistake, and should have been left blank. I think it would be a bigger mistake to invent a new predicate.

**Comment by nicholascar** [comment]
> SOSA rdfs:range is what it is is

Yeah but indeed it is what it is and unless I knock it out of out copy of SOSA, thereby making a non-standard SOSA, we have to live by it for not.

You know I'd prefer a standard property but not if it causes us reasoning issues.

So I don't think we have a better option than 3. for now.

**Comment by dr-shorthair** [comment]
> not if it causes us reasoning issues

What reasoning are you doing? I thought we were using SHACL for the design & validation, and SPARQL for query. No reasoning required.

**Comment by nicholascar** [comment]
> I thought the 'TERN Ontology' was defined in SHACL

No, it's an [OWL ontology](https://github.com/ternaustralia/ontology_tern/blob/master/docs/tern.ttl), with a separate [SHACL validator](https://github.com/ternaustralia/ontology_tern/blob/master/docs/tern.shacl.ttl).

> Can you turn-off data-type checking?

I don't think I can, not easily, in TQ EDG. 

I don't want to alter decade+ standard ways of working or implement much cutting edge stuff here, just make a 'normal' RDF system work. There is already enough innovation in the use of a graph data model, SHACL etc.

Please just implement a new property!

**Comment by dr-shorthair** [comment]
> I don't want to alter decade+ standard ways of working or implement much cutting edge stuff here

I understand. But we should resist altering the data in order to compensate for tooling limitations. Tools come and go (including schemas). Data is forever. 

And since queries go through chains of properties, we should be the most conservative about renaming those.

**Comment by dr-shorthair** [comment]
And if validation is all using SHACL, then just don't load the OWL ontology. 
We are not doing any reasoning here - we are just using RDF as a convenient data format. 
SHACL is really the closed-world complement to OWL/RDFS.

**Comment by nicholascar** [comment]
> I understand. But we should resist altering the data in order to compensate for tooling limitations. Tools come and go (including schemas). Data is forever.

We must be talking (typing?) at cross purposes. I am not suggesting altering any data, only providing properties that allow for the data, as Gaia have it, to be recorded without breaking any ontology rules.

> And since queries go through chains of properties, we should be the most conservative about renaming those.

You don't need to tell me: I advocate most strongly for property reuse. But the limit is here: if a property forces something you can't live with, we need a new property. Not a renamed one, a new one. Just as TERN already implements `tern:FeatureOfInterest` not `sosa:FeatureOfInterest` but we just can't relate the new property to the old with the `subPropertyOf` in this case for the RDFS reasoning issues mentioned.

> And if validation is all using SHACL, then just don't load the OWL ontology.

It's not and I can't as I already said. Within TopBraid EDG, the SOSA ontology is loaded and its reasoning will be applied. Not much I can do about it. Other than to create a hack SOSA...

> We are not doing any reasoning here - we are just using RDF as a convenient data format.

You might not be, but the BDR system will be. Also, other users of BDR data might, given that OWL ontologies allow for it.

> SHACL is really the closed-world complement to OWL/RDFS.

Sure, but we are inheriting a tricky rule from SOSA here, not arguing about what we can do with SHACL.

**Comment by edmondchuc** [comment]
Hi all, an update on my side.

- I've created a change request in SOSA to remove `sosa:resultTime rdfs:range xsd:dateTime`. https://github.com/w3c/sdw/issues/1338. 
- I've created a PR for a fix with option 3. https://github.com/ternaustralia/ontology_tern/pull/137

Please @dr-shorthair @nicholascar have a review and if we are all happy with it, we can merge it in.

I will create a new issue with links to all the relevant issues and pull requests to ensure things are not lost. Once SOSA has provided the upstream fix, we will revert back to using `sosa:resultTime` with deprecation messages for `tern:resultDateTime` in the form of property shapes.

@dr-shorthair out of curiosity, what is the process for change requests and how long does the process take?

**Comment by dr-shorthair** [comment]
> what is the process for change requests and how long does the process take?

Haha. There is currently no revision working group. So that request will just sit there (thanks for submitting it, though). 

Would be even better if it was a PR though - also on the spec document ...

**Comment by nicholascar** [comment]
Looks good to me, as I've stated in the PR.

**Comment by dr-shorthair** [comment]
And then RDF inherited this mess when they agreed to use the XML Schema datatypes, which was a political compromise in W3C.

**Comment by dr-shorthair** [comment]
>> Data is forever.
> We must be talking (typing?) at cross purposes. I am not suggesting altering any data

Here I was thinking of data-_files_, including the markup.
