### ISSUE TITLE
Create specialised classes of `tern:Site`

### ISSUE THREAD

**Issue by edmondchuc** [ternaustralia/ontology_tern#14]
Some of the well-defined concepts in ecology such as quadrats and transects are modelled as a Site. And the type of site is currently represented by a controlled vocabulary. Since transects are well-known concepts and have well-known properties such as `transect direction` and `transect start point`, it makes sense to model transects as a specialised class of `tern:Site`. 

The current site type controlled vocabulary is also small (3 concepts - plot, transect, quadrat) so the cost of creating these specialised classes is small.

**Comment by dr-shorthair** [comment]
However, see https://github.com/ternaustralia/ontology_tern/issues/8#issuecomment-889583973 

They may not be sub-classes.

**Comment by dr-shorthair** [comment]
1. Is each an individual `tern:Site` always expected to be the feature-of-interest of at least one observation? If not, then it should not be a sub-class of `sosa:FeatureOfInterest`
2. Why are `tern:Transect` and `tern:EcosystemProcessSite` sub-classes of `tern:Site`. Do they share all the attributes/properties of generic `tern:Site`? 
3. I suggest that `tern:Transect` and `tern:EcosystemProcessSite` are actually sub-classes of `sosa:Sample` - they are designed to be representative of some tract or landscape. 
4. The `dcterms:hasPart` relationship should be to `tern:Transect` or `tern:EcosystemProcessSite`, or maybe just their super-class `sosa:Sample`. I think you have confused subsumption and partonomy here (a common modeling error).

**Comment by edmondchuc** [comment]
https://github.com/ternaustralia/ontology_tern/pull/23 closes this issue. 

1. Each `tern:Site` is the ultimate feature of interest of any observation or sampling. But `tern:Site` is also a sample as it can relate to a larger feature of interest.
2. Transects, quadrats and subplots are subclasses of `tern:Sample`. 
3. See point 2.
4. `dcterms:hasPart` and `dcterms:isPartOf` are no longer used. `sosa:isSampleOf` is enough for our current requirements.
