### ISSUE TITLE
Create meta shapes to validate node and property shapes

### ISSUE THREAD

**Issue by edmondchuc** [ternaustralia/ontology_tern#149]
Ensure: 

- node shapes have exactly 1 `rdfs:label`
- property shapes have exactly 1 `sh:name` and `sh:description`
- Each `owl:Class` have exactly 1 `rdfs:label`
- Each `owl:Class` must ben an `rdfs:Class` and vice versa.

Create the file `meta.shapes.ttl` in the `docs/` directory.

All SHACL shape files must be validated in [`test.yml`](https://github.com/ternaustralia/ontology_tern/blob/master/.github/workflows/test.yml) workflow.

Ensure both `meta.shapes.ttl` and `tern.ecoplots.shapes.ttl` are validated for syntax errors.

Fix any broken tests.

**Comment by junrongYu** [comment]
We firstly add `rdfs:Class` for each `owl:Class` and vice versa. However, we decided to delete those `rdfs:class`.
