### ISSUE TITLE
Request for new controlled vocabulary terms

### ISSUE THREAD

**Issue by miekeGR** [ternaustralia/ontology_tern#160]
Hi TERN folks,

I have put together a list of terms that would be great to have access to in the TERN vocabulary options (details in the attached spreadsheet). These relate to providing options either when there is a lack of data from the source, or providing terms facilitating National Species List (NSL) name match Observations that we document for scientificNames matching closest to nationally recognised names for consistency. I am not wedded to the wording, feel free to adjust them. I'll summarise the list here:

**1. scientific name**
Request to add this term to the Feature Type vocabulary (in addition to Attributes and Parameter Type) so we can use a scientificName Value as a Feature of Interest for NSL name match Observation.
**2. generic site establishment**
Request this term be added to the Method Type list so we can create Sites where there has been no documentation of how the site was established.
**3. undefined taxon determination method**
Request this term be added to the Method Type list where source data is lacking.
**4. undefined field sub-sampling**
Request this term be added to the Method Type list where source data is lacking.
**5. NSL name match**
Request this term be added to the Method Type list to document NSL name matching Observations.
**6. number of NSL name matches**
Request this new Attribute be added so we can record the number of matches returned from the NSL from a single processed string value.

@edmondchuc let me know if you want me to walk you through the modelling for these terms.
[New TERN terms request 20220323.xlsx](https://github.com/ternaustralia/ontology_tern/files/8328627/New.TERN.terms.request.20220323.xlsx)

**Comment by edmondchuc** [comment]
Hi @miekeGR, can I get more clarification on **scientific name** please? I don't quite follow why this should be added to the Feature Type vocabulary.

The others look fine to me.

**Comment by miekeGR** [comment]
Sure, I'll do my best here with words, but happy to chat also. 

Essentially, we want use an Observation Collection of NSL Observations (there may be more than one) on a scientificName to represent the results of matching a scientificName string by the NSL. Observations need a Feature Of Interest and since it is the tern:Text value that we send to NSL for testing, I want to nominate the scientificName as the Feature Of Interest and hence needing a Feature Type term associated with it.

Example RDF here of a single name: _Banksia sessilis_ var. _cordata_, and just the relevant nodes:
@prefix dcterms: <http://purl.org/dc/terms/> .
@prefix dwc: <http://rs.tdwg.org/dwc/terms/> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix geo: <http://www.opengis.net/ont/geosparql#> .
@prefix prov: <http://www.w3.org/ns/prov#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix sosa: <http://www.w3.org/ns/sosa/> .
@prefix tern: <https://w3id.org/tern/ontologies/tern/> .
@prefix time: <http://www.w3.org/2006/time#> .
@prefix void: <http://rdfs.org/ns/void#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://example.org/scientificName-observation/4> a tern:Observation ;
    void:inDataset <http://example.org/dataset/margaret-river-flora> ;
    rdfs:comment "scientificName-observation" ;
    prov:wasAssociatedWith <http://example.org/Stream-Environment-and-Water-Pty-Ltd> ;
    sosa:hasFeatureOfInterest <http://example.org/specimen-sample/4> ;
    sosa:hasResult <http://example.org/scientificName/Banksia-sessilis-var-cordata> ;
    sosa:hasSimpleResult "Banksia sessilis var. cordata" ;
    sosa:observedProperty <http://linked.data.gov.au/def/tern-cv/70646576-6dc7-4bc5-a9d8-c4c366850df0> ;
    sosa:phenomenonTime [ a time:Instant ;
            rdfs:label "phenomenonTime" ;
            time:inXSDDate "2019-09-21"^^xsd:date ] ;
    tern:resultDateTime "2019-09-21"^^xsd:date ;
    sosa:usedProcedure <http://example.org/taxon-determination-method/> .

<http://example.org/scientificName/Banksia-sessilis-var-cordata> a tern:FeatureOfInterest,
        tern:Text,
        tern:Value ;
    rdfs:label "scientificName" ;
    void:inDataset <http://example.org/dataset/margaret-river-flora> ;
    rdf:value "Banksia sessilis var. cordata" ;
    tern:featureType <http://example.org/scientificName> .

<https://github.com/bio-org-au/nslapi/releases/tag/v0.0.4> a prov:Agent,
        prov:SoftwareAgent ;
    foaf:name "NSL name match API" .

<http://example.org/observationCollection/Banksia-sessilis-var-cordata> a tern:ObservationCollection ;
    prov:wasAssociatedWith <https://github.com/bio-org-au/nslapi/releases/tag/v0.0.4> ;
    sosa:hasFeatureOfInterest <http://example.org/scientificName/Banksia-sessilis-var-cordata> ;
    sosa:hasMember <http://example.org/observationNameMatch/Banksia-sessilis-var-cordata> .

<http://example.org/observationNameMatch/Banksia-sessilis-var-cordata> a tern:Observation ;
    void:inDataset <http://example.org/dataset/margaret-river-flora> ;
    rdfs:comment "NSL name match Observation" ;
    prov:wasAssociatedWith <https://github.com/bio-org-au/nslapi/releases/tag/v0.0.4> ;
    sosa:hasFeatureOfInterest <http://example.org/scientificName/Banksia-sessilis-var-cordata> ;
    sosa:hasResult <http://example.org/taxon/Banksia-sessilis-var-cordata> ;
    sosa:hasSimpleResult "Banksia sessilis var. cordata (Meisn.) A.R.Mast & K.R.Thiele" ;
    sosa:observedProperty <http://linked.data.gov.au/def/tern-cv/70646576-6dc7-4bc5-a9d8-c4c366850df0> ;
    sosa:phenomenonTime [ a time:Instant ;
            rdfs:label "phenomenonTime" ;
            time:inXSDDate "2022-03-15T08:48:15.003387+00:00"^^xsd:dateTimeStamp ] ;
    tern:resultDateTime "2022-03-15T08:48:15.003387+00:00"^^xsd:dateTimeStamp ;
    sosa:usedProcedure <http://example.org/procedure/nsl-name-match> .

**Comment by miekeGR** [comment]
Not sure why my cut and paste made all the @prefix capitalised? Please ignore.

**Comment by edmondchuc** [comment]
Hi @miekeGR please see if the revised data makes sense.

- Each observation is made on the same feature of interest (the specimen sample). 
- The first observation identifies the scientific name of the specimen. 
- The second observation identifies the accepted taxon in the NSL based on its scientific name. Document the algorithm in the procedure (e.g., using the scientific name..., match against the canonical names in NSL... and find the taxon with the accepted status).

```turtle

PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX tern: <https://w3id.org/tern/ontologies/tern/>
PREFIX time: <http://www.w3.org/2006/time#>
PREFIX void: <http://rdfs.org/ns/void#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

<http://example.org/scientificName-observation/4>
    a tern:Observation ;
    void:inDataset <http://example.org/dataset/margaret-river-flora> ;
    rdfs:comment "scientificName-observation" ;
    prov:wasAssociatedWith <http://example.org/Stream-Environment-and-Water-Pty-Ltd> ;
    sosa:hasFeatureOfInterest <http://example.org/specimen-sample/4> ;
    sosa:hasResult <http://example.org/scientificName/Banksia-sessilis-var-cordata> ;
    sosa:hasSimpleResult "Banksia sessilis var. cordata" ;
    sosa:observedProperty <http://linked.data.gov.au/def/tern-cv/56195246-ec5d-4050-a1c6-af786fbec715> ; # scientific name
    sosa:phenomenonTime [
            a time:Instant ;
            rdfs:label "phenomenonTime" ;
            time:inXSDDate "2019-09-21"^^xsd:date
        ] ;
    sosa:usedProcedure <http://example.org/taxon-determination-method/> ;
    tern:resultDateTime "2019-09-21"^^xsd:date ;
.

<http://example.org/Stream-Environment-and-Water-Pty-Ltd>
    a
        prov:Agent ,
        prov:Organization ;
.

<http://example.org/observationNameMatch/Banksia-sessilis-var-cordata>
    a tern:Observation ;
    void:inDataset <http://example.org/dataset/margaret-river-flora> ;
    rdfs:comment "NSL name match Observation" ;
    prov:wasAssociatedWith <https://github.com/bio-org-au/nslapi/releases/tag/v0.0.4> ;
    sosa:hasFeatureOfInterest <http://example.org/specimen-sample/4> ; # on the specimen
    sosa:hasResult [
            a tern:IRI ;
            rdf:value <https://id.biodiversity.org.au/name/apni/205183> # IRI of the accepted taxon in NSL
        ] ;
    sosa:hasSimpleResult "Banksia sessilis var. cordata (Meisn.) A.R.Mast & K.R.Thiele" ;
    sosa:observedProperty <http://linked.data.gov.au/def/tern-cv/70646576-6dc7-4bc5-a9d8-c4c366850df0> ;
    sosa:phenomenonTime [
            a time:Instant ;
            rdfs:label "phenomenonTime" ;
            time:inXSDDateTimeStamp "2022-03-15T08:48:15.003387+00:00"^^xsd:dateTimeStamp
        ] ;
    sosa:usedProcedure <http://example.org/procedure/nsl-name-match> ;
    tern:resultDateTime "2022-03-15T08:48:15.003387+00:00"^^xsd:dateTimeStamp ;
.

<http://example.org/specimen-sample/4>
    a tern:FeatureOfInterest ;
    void:inDataset <http://example.org/dataset/margaret-river-flora> ;
    tern:featureType <http://linked.data.gov.au/def/tern-cv/2e122e23-881c-43fa-a921-a8745f016ceb> ;
.

<https://github.com/bio-org-au/nslapi/releases/tag/v0.0.4>
    a
        prov:Agent ,
        prov:SoftwareAgent ;
    foaf:name "NSL name match API" ;
.

<http://example.org/scientificName/Banksia-sessilis-var-cordata>
    a
        tern:Text ,
        tern:Value ;
    rdfs:label "scientificName" ;
    void:inDataset <http://example.org/dataset/margaret-river-flora> ;
    rdf:value "Banksia sessilis var. cordata" ;
    tern:featureType <http://example.org/scientificName> ;
.


```
![Screen Shot 2022-03-25 at 12 55 34 pm](https://user-images.githubusercontent.com/37032744/160045568-0b7a8007-2936-4884-9ad1-174a48f89644.png)

**Comment by miekeGR** [comment]
Hi @edmondchuc thanks for that. Your model looks just like my initial model, but then I thought it was not right because the NSL isn't making an observation of the sample, it is the scientificName that it is observing. Do you think linking to the sample still works?

**Comment by edmondchuc** [comment]
I understand where you are coming from. In a different situation, it may work, but I can't think of an example right now. Let me try and explain my perspective below with an example.

Say you have a tennis ball and you wanted to measure its circumference. Using the SOSA model, the measurement is modelled as a result of an observation on the tennis ball's circumference. Later on, you decide to calculate the volume of the tennis ball. Calculating the volume of the tennis ball depends on the previously recorded value for circumference. This dependence does not mean the feature of interest of the volume observation changes to the circumference value. The feature of interest still remains as the tennis ball. As part of the procedure, you would document how the volume is calculated and show the formula used, which includes the circumference.

Going back to your example, the taxon identification observation's feature of interest would also not change to the scientific name despite its dependence on the scientific name to match against the NSL's list of taxons.

Let me know if you agree or not and if I misunderstood something from my side.

**Comment by miekeGR** [comment]
Thanks @edmondchuc I like your tennis ball analogy, but I still think that it doesn't quite line up with the NSL name match situation. I hope I can illustrate the difference by an extension of the tennis ball situation. Imagine there were 2 different measurements of the circumference of the tennis ball; maybe done by different people, on different days, using a different tape measure that gave 2 different results. The method to determine the volume does not single out which circumference was used as your value to calculate volume if the only link to the volume observation is the sample. 

With the model I have drawn out for the NSL name match, it is possible to have 2 (or more) different name labels associated with a sample, but to know which name was sent to the NSL is ambiguous unless the connection is drawn to the name value that was sent to the NSL. The protocol the NSL uses to match the name does not tell you what value was provided to it to get the result unless we were to have a protocol for every name we ever sent to the NSL.

Does this muddy the water a little about where the Feature of Interest lies?

**Comment by edmondchuc** [comment]
Hi @miekeGR I share your concern in terms of the lack of relationship or acknowledgement as to which/what scientific name was used in an NSL name match.

I had a look at SOSA/SSN because I remembered there exists `ssn:hasInput` and `ssn:hasOutput` properties but I am not entirely clear how they should be used. It is a bit underdocumented in https://www.w3.org/TR/vocab-ssn/. The problem I see with using `ssn:hasInput` is that it is a property on the Procedure. This complicates things because the way we use the value node of `sosa:usedProcedure` is directly to a controlled vocabulary term identified by an IRI. Unless we change this, we can't use `ssn:hasInput`. 

In any case, I still think the example I gave is valid. The only thing missing is expressing what the input values are. Maybe we can create a standard practice to express input values directly on the Observation itself. Have first-class support for it by introducing new properties, e.g., `tern:inputValue` or express it through an Attribute on the Observation.

**Comment by miekeGR** [comment]
Oh yes @edmondchuc, I like your thinking!! The tern:inputValue directly on the Observation sounds good to me. So, something like this?

PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX tern: <https://w3id.org/tern/ontologies/tern/>
PREFIX time: <http://www.w3.org/2006/time#>
PREFIX void: <http://rdfs.org/ns/void#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

<http://example.org/scientificName-observation/4>
    a tern:Observation ;
    void:inDataset <http://example.org/dataset/margaret-river-flora> ;
    rdfs:comment "scientificName-observation" ;
    prov:wasAssociatedWith <http://example.org/Stream-Environment-and-Water-Pty-Ltd> ;
    sosa:hasFeatureOfInterest <http://example.org/specimen-sample/4> ;
    sosa:hasResult <http://example.org/scientificName/Banksia-sessilis-var-cordata> ;
    sosa:hasSimpleResult "Banksia sessilis var. cordata" ;
    sosa:observedProperty <http://linked.data.gov.au/def/tern-cv/56195246-ec5d-4050-a1c6-af786fbec715> ; # scientific name
    sosa:phenomenonTime [
            a time:Instant ;
            rdfs:label "phenomenonTime" ;
            time:inXSDDate "2019-09-21"^^xsd:date
        ] ;
    sosa:usedProcedure <http://example.org/taxon-determination-method/> ;
    tern:resultDateTime "2019-09-21"^^xsd:date ;
.

<http://example.org/Stream-Environment-and-Water-Pty-Ltd>
    a
        prov:Agent ,
        prov:Organization ;
.

<http://example.org/observationNameMatch/Banksia-sessilis-var-cordata>
    a tern:Observation ;
    void:inDataset <http://example.org/dataset/margaret-river-flora> ;
    rdfs:comment "NSL name match Observation" ;
    prov:wasAssociatedWith <https://github.com/bio-org-au/nslapi/releases/tag/v0.0.4> ;
    tern:inputValue <http://example.org/scientificName/Banksia-sessilis-var-cordata> #IRI of the scientificName text value
    sosa:hasFeatureOfInterest <http://example.org/specimen-sample/4> ; # on the specimen
    sosa:hasResult [
            a tern:IRI ;
            rdf:value <https://id.biodiversity.org.au/name/apni/205183> # IRI of the accepted taxon in NSL
        ] ;
    sosa:hasSimpleResult "Banksia sessilis var. cordata (Meisn.) A.R.Mast & K.R.Thiele" ;
    sosa:observedProperty <http://linked.data.gov.au/def/tern-cv/70646576-6dc7-4bc5-a9d8-c4c366850df0> ;
    sosa:phenomenonTime [
            a time:Instant ;
            rdfs:label "phenomenonTime" ;
            time:inXSDDateTimeStamp "2022-03-15T08:48:15.003387+00:00"^^xsd:dateTimeStamp
        ] ;
    sosa:usedProcedure <http://example.org/procedure/nsl-name-match> ;
    tern:resultDateTime "2022-03-15T08:48:15.003387+00:00"^^xsd:dateTimeStamp ;
.

<http://example.org/specimen-sample/4>
    a tern:FeatureOfInterest ;
    void:inDataset <http://example.org/dataset/margaret-river-flora> ;
    tern:featureType <http://linked.data.gov.au/def/tern-cv/2e122e23-881c-43fa-a921-a8745f016ceb> ;
.

<https://github.com/bio-org-au/nslapi/releases/tag/v0.0.4>
    a
        prov:Agent ,
        prov:SoftwareAgent ;
    foaf:name "NSL name match API" ;
.

<http://example.org/scientificName/Banksia-sessilis-var-cordata>
    a
        tern:Text ,
        tern:Value ;
    rdfs:label "scientificName" ;
    void:inDataset <http://example.org/dataset/margaret-river-flora> ;
    rdf:value "Banksia sessilis var. cordata" ;
.

**Comment by edmondchuc** [comment]
I think I would prefer the `tern:inputValue` link to the observation rather than the result directly. I'm still playing around with the property name. Here's the same thing but using `tern:hasInputValueFrom` on the NSL observation and linking to the scientific name observation.

@dr-shorthair I'd love to get your thoughts on this.

```turtle

PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX tern: <https://w3id.org/tern/ontologies/tern/>
PREFIX time: <http://www.w3.org/2006/time#>
PREFIX void: <http://rdfs.org/ns/void#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

<http://example.org/scientificName-observation/4>
    a tern:Observation ;
    void:inDataset <http://example.org/dataset/margaret-river-flora> ;
    rdfs:comment "scientificName-observation" ;
    prov:wasAssociatedWith <http://example.org/Stream-Environment-and-Water-Pty-Ltd> ;
    sosa:hasFeatureOfInterest <http://example.org/specimen-sample/4> ;
    sosa:hasResult <http://example.org/scientificName/Banksia-sessilis-var-cordata> ;
    sosa:hasSimpleResult "Banksia sessilis var. cordata" ;
    sosa:observedProperty <http://linked.data.gov.au/def/tern-cv/56195246-ec5d-4050-a1c6-af786fbec715> ; # scientific name
    sosa:phenomenonTime [
            a time:Instant ;
            rdfs:label "phenomenonTime" ;
            time:inXSDDate "2019-09-21"^^xsd:date
        ] ;
    sosa:usedProcedure <http://example.org/taxon-determination-method/> ;
    tern:resultDateTime "2019-09-21"^^xsd:date ;
.

<http://example.org/Stream-Environment-and-Water-Pty-Ltd>
    a
        prov:Agent ,
        prov:Organization ;
.

<http://example.org/observationNameMatch/Banksia-sessilis-var-cordata>
    a tern:Observation ;
    void:inDataset <http://example.org/dataset/margaret-river-flora> ;
    rdfs:comment "NSL name match Observation" ;
    prov:wasAssociatedWith <https://github.com/bio-org-au/nslapi/releases/tag/v0.0.4> ;
    sosa:hasFeatureOfInterest <http://example.org/specimen-sample/4> ; # on the specimen
    tern:hasInputValueFrom <http://example.org/scientificName-observation/4> ;
    sosa:hasResult [
            a tern:IRI ;
            rdf:value <https://id.biodiversity.org.au/name/apni/205183> # IRI of the accepted taxon in NSL
        ] ;
    sosa:hasSimpleResult "Banksia sessilis var. cordata (Meisn.) A.R.Mast & K.R.Thiele" ;
    sosa:observedProperty <http://linked.data.gov.au/def/tern-cv/70646576-6dc7-4bc5-a9d8-c4c366850df0> ;
    sosa:phenomenonTime [
            a time:Instant ;
            rdfs:label "phenomenonTime" ;
            time:inXSDDateTimeStamp "2022-03-15T08:48:15.003387+00:00"^^xsd:dateTimeStamp
        ] ;
    sosa:usedProcedure <http://example.org/procedure/nsl-name-match> ;
    tern:resultDateTime "2022-03-15T08:48:15.003387+00:00"^^xsd:dateTimeStamp ;
.

<http://example.org/specimen-sample/4>
    a tern:FeatureOfInterest ;
    void:inDataset <http://example.org/dataset/margaret-river-flora> ;
    tern:featureType <http://linked.data.gov.au/def/tern-cv/2e122e23-881c-43fa-a921-a8745f016ceb> ;
.

<https://github.com/bio-org-au/nslapi/releases/tag/v0.0.4>
    a
        prov:Agent ,
        prov:SoftwareAgent ;
    foaf:name "NSL name match API" ;
.

<http://example.org/scientificName/Banksia-sessilis-var-cordata>
    a
        tern:Text ,
        tern:Value ;
    rdfs:label "scientificName" ;
    void:inDataset <http://example.org/dataset/margaret-river-flora> ;
    rdf:value "Banksia sessilis var. cordata" ;
    tern:featureType <http://example.org/scientificName> ;
.


```
![Screen Shot 2022-03-28 at 10 37 27 am](https://user-images.githubusercontent.com/37032744/160308649-142941e0-be55-4504-9a3d-58bb7699c915.png)

**Comment by dr-shorthair** [comment]
@miekeGR it wouldn't be usual to have a `sosa:Observation` as the value of a `hasResult`. 
If a result of a previous observation is part of the story, then that would be captured as part of the _procedure_ (general) or _sensor_ i.e. observer (specific).

**Comment by miekeGR** [comment]
Thanks @edmondchuc I can see where linking the observations rather than the value would work since the result is the obvious value that would be used.

And thanks also @dr-shorthair , but I do not exactly follow what you mean. Are you saying it would be better to have the input value linked to the procedure rather than the observation? If so, how do you differentiate which result comes from which input if you use the same procedure again with another value as input?

**Comment by edmondchuc** [comment]
@miekeGR, the terms exist now.

**generic site establishment**
IRI: http://linked.data.gov.au/def/tern-cv/a1685655-f8e2-46ee-9a74-767c648b54f4

**undefined taxon determination method**
IRI: http://linked.data.gov.au/def/tern-cv/2eef4e87-beb3-449a-9251-f59f5c07d653

**undefined field sub-sampling**
IRI: http://linked.data.gov.au/def/tern-cv/7930424c-f2e1-41fa-9128-61524b67dbd5

**NSL name match**
IRI: http://linked.data.gov.au/def/tern-cv/526319d0-0210-42b0-bd4c-fa18585ab6f2

**number of NSL name matches**
IRI: http://linked.data.gov.au/def/tern-cv/8b7b7346-4317-4bcc-9ff9-24dbf8e9c637

I've added a generic definition to each one. Let me know if you would like any modifications to any of them.

**Comment by miekeGR** [comment]
That's awesome, thanks @edmondchuc I'll check out those definitions when the controlled vocabularies page is back up.

**Comment by edmondchuc** [comment]
@miekeGR yes sorry about that. Our data centres are upgrading today and some services are affected. At the latest, they should be back up tomorrow.

**Comment by edmondchuc** [comment]
The original request to create the controlled vocabs is now completed. Can we close this now? 

@miekeGR if you want to discuss further on the scientific name modelling, please create a new issue. Cheers.

**Comment by miekeGR** [comment]
Cheers, thanks @edmondchuc , we can close this and I'll create a new one for the tern:hasInputValueFrom

**Comment by edmondchuc** [comment]
Since observations and samplings are activities, we can use `prov:wasInformedBy` to express dependencies between them.

> An activity a2 is dependent on or informed by another activity a1, by way of some unspecified entity that is generated by a1 and used by a2.

```turtle
@prefix prov: <http://www.w3.org/ns/prov#> .

<http://example.org/observationNameMatch/Banksia-sessilis-var-cordata>
    prov:wasInformedBy <http://example.org/scientificName-observation/4> . 
```

This RDF snippet says that the observation `<http://example.org/observationNameMatch/Banksia-sessilis-var-cordata>` is dependent on the `<http://example.org/scientificName-observation/4>` and its generated entity (result).

See https://www.w3.org/TR/prov-o/#wasInformedBy.

Ignore the suggestionin https://github.com/ternaustralia/ontology_tern/issues/160#issuecomment-1080062852 on using a new property such as `tern:hasInputValueFrom`.

**Comment by miekeGR** [comment]
Hi @edmondchuc this is great! Thanks for that I was just about to open a new issue to follow this one up and now I don't have to ;-) I'll update my model.

Cheers

**Comment by dr-shorthair** [comment]
PROV-O summary is here: https://www.w3.org/TR/prov-o/#description-starting-point-terms 

Mapping of SOSA classes to PROV-O is https://www.w3.org/TR/vocab-ssn/#PROV_Alignment_class
