### ISSUE TITLE
Shape error for Sample

### ISSUE THREAD

**Issue by nicholascar** [ternaustralia/ontology_tern#162]
Sample has this property restriction:

```turtle
tern-shapes:Sample-isResultOf
    a sh:PropertyShape ;
    sh:class tern:Sampling ;
    sh:description "Relation linking a Result to the Observation or Actuation or act of Sampling that created or caused it." ;
    sh:minCount 1 ;
    sh:name "sosa:isResultOf" ;
    sh:nodeKind sh:IRI ;
    sh:path sosa:isResultOf ;
.
```

So this requires _a minimum of_ one `sosa:isResultOf`.

However, Sample inherits from Result and thus has this restriction:

```turtle
tern-shapes:Result-isResultOf
    a sh:PropertyShape ;
    sh:description "Relation linking a Result to the Observation or Actuation or act of Sampling that created or caused it." ;
    sh:maxCount 1 ;
    sh:minCount 1 ;
    sh:name "sosa:isResultOf" ;
    sh:nodeKind sh:IRI ;
    sh:or (
            [ sh:class tern:Observation ]
            [ sh:class tern:Sampling ]
        ) ;
    sh:path sosa:isResultOf ;
.
```

This requires _exactly 1_ `sosa:isResultOf`.

The error here is that the Sample restriction is more permissive than the Result restriction. I could have a Sample with 2 `sosa:isResultOf` values, which would be fine according to Sample's restriction (min 1) but invalid according to Results's restriction (exactly 1).

**Comment by edmondchuc** [comment]
Thanks @nicholascar. I think the sample's property shape should say:

```turtle
tern-shapes:Sample-isResultOf
    a sh:PropertyShape ;
    sh:class tern:Sampling ;
    sh:name "sosa:isResultOf" ;
    sh:path sosa:isResultOf ;
.
```

The min/max count and node kind is already expressed in `tern-shapes:Result-isResultOf`.

Do you agree?

Related issue: https://github.com/ternaustralia/ontology_tern/issues/109

**Comment by nicholascar** [comment]
Yes, that's a solution. That's restricting the range to a Sampling, down from Observation or Sampling - fine - and not touching cardinality.

**Comment by edmondchuc** [comment]
Awesome thanks @nicholascar, I will get this in on the next release.
