### ISSUE TITLE
Suggest range value of sosa:usedProcedure & tern:samplingType should be skos:Concept

### ISSUE THREAD

**Issue by nicholascar** [ternaustralia/ontology_tern#163]
The current Property Shape for Sampling's `sosa:usedProcedure` & `tern:samplingType` restrict to `sh:IRI` but, I assume, Concepts from vocabularies are expected to be used here. If I'm correct, should these shapes further restrict the range value to not just `sh:IRI` but to `skos:Concept`?

**Comment by edmondchuc** [comment]
Yes, they will primarily be SKOS concepts but I left it open-ended because I was not sure if it was feasible for the BDR to create controlled vocabularies for each ingested dataset. For example, without restricting `sosa:usedProcedure`, datasets can link to a PDF URL of the procedure.

The kind of restriction you suggested will be added to TERN's [EcoPlots shapes](https://github.com/ternaustralia/ontology_tern/blob/master/docs/tern.ecoplots.shapes.ttl) (empty for now) since in TERN's system, all of the values of `sosa:usedProcedure` and `tern:samplingType` are SKOS concepts.

**Comment by miekeGR** [comment]
Thanks @nicholascar and @edmondchuc . Some members of our team have been trying to work out how to assemble a vocabulary for sosa:usedProcedure and have suggested that it is not feasible because of how much variation there may be in the data. The other issue we are facing is there are times when we will not be able to source an original document to reference protocols either e.g. for museum or herbarium data. So, I was wondering if we can add the option of a literal value to be able to capture what information we do have.

**Comment by nicholascar** [comment]
> trying to work out how to assemble a vocabulary for sosa:usedProcedure and have suggested that it is not feasible because of how much variation there may be in the data

I think the best solution is this:

**Create a hierarchical vocabulary.**

If you have a hierarchical vocab, then you can have high-level, generic, concepts for procedures which mean that every `Sampling` is always possible to allocate a defined procedure for, even if it's trivial. Then you extend downwards for specific procedures.

Even if you have 1,000,000+ specific procedures, you can just mint IDs for every single one of those 1M items - essentially registering the procedure text with an ID. And then just categorise them as best you can within the hierarchical vocab. If you need to link off to publicly available documents for the whole procedure, you can use simple `dcterms:source`, if quoting a hyperlink` or `dcterms:provenance` if you're going to describe the source in works, e.g. "Procedure source is Section 3, Chapter 5, Smith & Jones 2010...).

If you make IDs for the procedures that are not tied to the vocabulary structure, e.g. UUIDs, then you can create IDs for all procedures and then the hierarchy can be improved over time without any ID changes needed. This is known vocab best practice.

I'm very happy to help further in solving this procedures vocab problem! I can also assist with more complex bibliographic referencing in RDF if needed as we do this in other projects.

**Comment by miekeGR** [comment]
@nicholascar it would be so great to sort out this issue. I really appreciate your offer of help. I'll DM you to arrange a time to look into it.

**Comment by edmondchuc** [comment]
Thanks @nicholascar, I agree, best to use opaque IRIs. 

@miekeGR's recently requested some generic methods which are now available. See https://github.com/ternaustralia/ontology_tern/issues/160#issuecomment-1080282609. 

The generic methods were created under the collection [General Ecological Field Survey Methods](http://linked.data.gov.au/def/tern-cv/4c489862-0348-4ed8-afae-ed5bb296b034).

New methods can go into this collection and have narrower/broader (hierarchical relationships as suggested by @nicholascar.

**Comment by nicholascar** [comment]
@miekeGR and I have worked on Gaia creating a vocab as described above. It seems do-able. The BDR can host it and Gaia can add methods to it easily enough, as they encounter distinct method descriptions. Refactoring/categorisation can be undertaken later.

**Comment by edmondchuc** [comment]
Cool, sounds good @nicholascar. 

Any other comments for https://github.com/ternaustralia/ontology_tern/issues/163#issuecomment-1085251195? Or can this issue be closed?

**Comment by dr-shorthair** [comment]
1. if you have a large set (more than a few hundred max) then opaque URIs are usually safest. If the set is smaller, then memorability is possible, so non-opaque should be considered, providing you have a suitable was of managing them. 

2. range = `sh:IRI` always makes me a little uncomfortable. Is it essentially the same as `owl:ObjectProperty`? Can you have a union-type which has a `skos:Concept` if inlined, else a URI if remote?

**Comment by nicholascar** [comment]
> Can you have a union-type which has a skos:Concept if inlined, else a URI if remote?

If this is possible, I support it.

Perhaps it's possible to implement a Shape that has some sort of logic in it which looks for the in-lined-ness, i.e. if the object of triples with predicate `sosa:usedProcedure` & `tern:samplingType` also appears as a subject in the graph being validated, there must be a triple of `<object> a skos:Concept`. 

Having said that: it's actually a pain to have to ensure that every Concept referenced in data does declare that it is indeed a Concept: think about the fact that we hope that eventually almost all of the data coming in to the BDR is reusing existing Concepts from vocabs and that just referencing them and not having to bother that they are also defined, in the messages, as a Concept all over again.

You know, why don't you close this - so leave a test for `sh:IRI` only - and then in the BDR itself we can implement a variant test that checks for `skos:Concept`? i.e., the data in the DB must link up and be a Concept but inbound data need only provide the IRI. 

I guess it's the difference between validating messages for data exchange and data at rest in a BD...

**Comment by edmondchuc** [comment]
> Perhaps it's possible to implement a Shape that has some sort of logic in it which looks for the in-lined-ness, i.e. if the object of triples with predicate `sosa:usedProcedure` & `tern:samplingType` also appears as a subject in the graph being validated, there must be a triple of `<object> a skos:Concept`.

I think this is possible with `sh:sparql`.

> You know, why don't you close this - so leave a test for sh:IRI only - and then in the BDR itself we can implement a variant test that checks for skos:Concept? i.e., the data in the DB must link up and be a Concept but inbound data need only provide the IRI.
>
> I guess it's the difference between validating messages for data exchange and data at rest in a BD...

I agree! We're doing the same thing for the EcoPlots system.
