### ISSUE TITLE
Potential Logic issue in site

### ISSUE THREAD

**Issue by peterphilips** [ternaustralia/ontology_tern#169]
https://linkeddata.tern.org.au/viewers/tern-ontology?uri=https://w3id.org/tern/ontologies/tern/Site

Underneath the rows of 'Properties from Sample', the cardinality of sosa:isResultOf is a minimum of 1, but underneath the heading 'Properties from Result' the sosa:isResultOf is exactly 1.

**Comment by edmondchuc** [comment]
Duplicate of https://github.com/ternaustralia/ontology_tern/issues/162
