### ISSUE TITLE
Allow for tern:Sample instances to exist without the need to have a tern:Sampling

### ISSUE THREAD

**Issue by edmondchuc** [ternaustralia/ontology_tern#192]
Currently the [`tern:Sample`](https://w3id.org/tern/ontologies/tern/Sample) class is a subclass of [`tern:Result`](https://w3id.org/tern/ontologies/tern/Result) and inherits the constraint from `tern:Result`. 

The constraint is:
> A Result requires exactly 1 `sosa:isResultOf` predicate.

This effectively means that all samples, whether it is used as a proxy or to represent a subset of the ultimate feature of interest must have a relationship to a `tern:Sampling` via the `sosa:isResultOf` predicate. In some cases, this requirement does not make sense and only makes the data more verbose. 

There may be more cases but currently I see two main cases for using `tern:Sampling`:

1. Used in a sampling campaign, think collecting soil, fauna, or flora samples.
2. Used for proxy samples such as (sub-)sites and transects where you can capture the "setup" details and procedure in the sampling activity. Usually these samples are not features of interest of scientific observations but they may have sub-samples that are.

### Examples - Where a sampling activity does not make sense

The "sample" highlighted in red does not meet case 1 or 2, instead it only represents the thing we are sampling with the camera trap. The current constraints for a `tern:Result` requires a `sosa:isResultOf` predicate to exist for the fauna community. If we had to create a sampling activity for the fauna community, what would be the procedure? What other properties would the sampling activity have? And what purpose is it serving?

<img width="1229" alt="Screen Shot 2022-06-02 at 11 47 21 am" src="https://user-images.githubusercontent.com/37032744/171529793-5aad8f8b-25ec-498a-a58d-83f5fe3cccbe.png">

Another example where a mandatory sampling activity does not make sense is on sampling points along transects. These sampling points are "sub-samples" of the transect but they are only there to provide intermediary information for further sub-samples that are of interest at the domain level. Such further sub-samples may be plant community, land surface, etc at a particular sampling point.

### Proposal

Looking more closely at the [examples from the SSN spec](https://www.w3.org/TR/vocab-ssn/#examples), most of the samples do not have an associated sampling activity.

My proposal is to change the constraint for `tern:Result` to optionally have a `sosa:isResultOf` predicate to allow for samples to exist without a link to a sampling activity.

**Comment by dr-shorthair** [comment]
>  all samples, [...] must have a relationship to a tern:Sampling 

The word 'must' may be the problem here. 

From an ontology perspective, it is actually 'all samples _have_ a relationship to a tern:Sampling ' but the OWA means that it does not have to be ('must') included in any particular payload. The examples in the SSN spec reflect that.  

It is only if you back up the cardinality constraint in the `owl:Restriction` with a SHACL that _enforces_ this that it might be annoying. 

It is unclear above whether you are proposing to change the OWL or the SHACL.

**Comment by edmondchuc** [comment]
Thanks @dr-shorthair. I'm proposing to change the SHACL.

**Comment by dr-shorthair** [comment]
OK. The SHACL was overly strict then, for your application. Better fix it.

**Comment by edmondchuc** [comment]
Thanks, I just wanted to check my thinking with you before I make any changes. I'll make a PR today or tomorrow.

FYI @miekeGR
