### ISSUE TITLE
global match vs global value

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [ternaustralia/ontology_tern#2]
Fix duplicate properties and their descriptions - global match, global value

**Comment by edmondchuc** [comment]
I remember now - tern:globalMatch is used to link between controlled vocabularies (e.g. a concept in CORVEG to a concept in TERN) while tern:globalValue is used to link e.g. tern:ObservableProperty with the source parameter (CORVEG) to the global parameter (TERN).
