### ISSUE TITLE
Attempts to access the Parameters vocabulary results in a Internal Server Error

### ISSUE THREAD

**Issue by miekeGR** [ternaustralia/ontology_tern#213]
![image](https://github.com/ternaustralia/ontology_tern/assets/80197455/b9d3bcfc-1bf6-4659-b00c-5c81946e27d7)

Occasionally over the past few months, I have been trying to access the Parameters vocabulary (link https://linkeddata.tern.org.au/viewer/tern/id/http://linked.data.gov.au/def/tern-cv/5699eca7-9ef0-47a6-bcfb-9306e0e2b85e), but I get an internal server error:

![2023-05-11_12h35_13](https://github.com/ternaustralia/ontology_tern/assets/80197455/615dce35-41a7-46e1-ac78-aba9fb3356d2)

Instead of just hoping next time I try to open it, it will work, I thought I'd raise it here as an issue.

Thanks in advance if you are able to fix it. The other links in that menu resolve.

**Comment by smguru** [comment]
@miekeGR thank you for raising the issue, we will get back to you.

**Comment by smguru** [comment]
Hello @miekeGR , we have upgraded the linkeddata viewer and the parameter should be available https://linkeddata.tern.org.au/prez/tern-cv/v/vocab/trn-cv:5699eca7-9ef0-47a6-bcfb-9306e0e2b85e
