### ISSUE TITLE
Functional Properties - Legend vs Content in doco

### ISSUE THREAD

**Issue by gwittich** [ternaustralia/ontology_tern#36]
The ‘Legend’ includes ‘**Functional Properties**’ but there is no details as to what they are in the documentation at   https://ternaustralia.github.io/ontology_tern
Gail Wittich - Gaia Resources

**Comment by edmondchuc** [comment]
The legend in pyLODE is referring to Functional Properties as in the OWL class [owl:FunctionalProperty](http://www.w3.org/2002/07/owl#FunctionalProperty), which the TERN Ontology does not define any.

Closing this issue as it is not related directly to the core information model.
