### ISSUE TITLE
Lack of 'Named Individuals' content

### ISSUE THREAD

**Issue by gwittich** [ternaustralia/ontology_tern#37]
The ‘Legend’  at https://ternaustralia.github.io/ontology_tern/  includes ‘**Named Individuals**’ but there is content in the relevant section in the Doco.
Gail Wittich - Gaia Resources

**Comment by dr-shorthair** [comment]
There may not be any individuals in the ontology. 
It would be better if pyLODE suppressed that section, but it is not necessarily an error.

**Comment by nicholascar** [comment]
Confirming that this is a pyLODE bug, not really a TERN Ontology thing.

**Comment by edmondchuc** [comment]
Closing as this is related to pyLODE documentation. 

In regards to why the named individual shows up without any content, I think it is because the named individuals are defined with blank nodes, but I could be wrong.
