### ISSUE TITLE
'Concept' - duplicate content in doco

### ISSUE THREAD

**Issue by gwittich** [ternaustralia/ontology_tern#38]
‘Concept’ occurs twice  as a class in the ontology:
https://ternaustralia.github.io/ontology_tern/#Concept
https://ternaustralia.github.io/ontology_tern/#Concept1
Gail Wittich - Gaia Resources

**Comment by dr-shorthair** [comment]
Those URIs are links to two different places in the HTML document. 
The class identifiers are 
- `http://linked.data.gov.au/def/datatype/Concept`
- `https://w3id.org/tern/ontologies/tern/Concept`

These are distinct resources because the URIs are different.

**Comment by edmondchuc** [comment]
@dr-shorthair is right. They are pointing to 2 different resources. However, this should no longer be an issue since the small datatype vocabulary has been removed as a dependency.
