### ISSUE TITLE
‘Material Sample’ Class doco

### ISSUE THREAD

**Issue by gwittich** [ternaustralia/ontology_tern#39]
‘Material Sample’ occurs twice in the list of Classes at https://ternaustralia.github.io/ontology_tern/#Concept in the ontology (it is only detailed once)

Gail Wittich - Gaia Resources

**Comment by dr-shorthair** [comment]
There are two different classes:
- `http://rs.tdwg.org/dwc/terms/MaterialSample` from Darwin Core
- `https://w3id.org/tern/ontologies/tern/MaterialSample` from the TERN Ontology

The URIs are different, even though the labels are similar (there is a case difference). It is the URI that matters.

**Comment by edmondchuc** [comment]
The `http://rs.tdwg.org/dwc/terms/MaterialSample` declaration as a class has been removed. The TERN `https://w3id.org/tern/ontologies/tern/MaterialSample` still aligns with Darwin Core by subclassing.
