### ISSUE TITLE
‘Site’ vs 'Ecological Site' 

### ISSUE THREAD

**Issue by gwittich** [ternaustralia/ontology_tern#40]
‘Site’ occurs on the 'Overview' at https://ternaustralia.github.io/ontology_tern/overview.png but does not occur at all in the list of Classes. 
However 'Ecological Site' does occur in the ist of Classes. 

Gail Wittich - Gaia Resources

**Comment by dr-shorthair** [comment]
The URI for the class is `https://w3id.org/tern/ontologies/tern/Site`. 
This is usually abbreviated to `tern:Site` using the prefix `tern:` for `https://w3id.org/tern/ontologies/tern/` (though any string could be declared and used as the prefix - the RDF processor will expand it to the URI internally anyway). 

The 'definition' of the class has the annotation `rdfs:label "Ecological Site"` which provides a more human-readable denotation, but this is just a label.

**Comment by nicholascar** [comment]
This is exactly why I prefer class names to match class labels with only spaces and special characters removed!

So the class should be `tern:EcologicalSite` or the label should just be "Site"...

**Comment by edmondchuc** [comment]
Proposal:
- Rename `rdfs:label` to `Site`
- Describe in the `skos:definition` this `Site` is an ecological monitoring site.
