### ISSUE TITLE
Single source of truth for documentation

### ISSUE THREAD

**Issue by gwittich** [ternaustralia/ontology_tern#41]
What is the point of truth in terms of documentation?

> https://linkeddata-dev.tern.org.au/tern-ontology

or

> https://ternaustralia.github.io/ontology_tern/

> or something else?

Gail Wittich - Gaia Resources

**Comment by nicholascar** [comment]
TERN (Edmond) says that the linkeddata-dev version is the maintained one.

**Comment by edmondchuc** [comment]
The prod version is accessible online at https://linkeddata.tern.org.au/information-models/tern-ontology.
