### ISSUE TITLE
Darwin Core data example for mapping to NDES

### ISSUE THREAD

**Issue by miekeGR** [ternaustralia/ontology_tern#46]
Hi Edmond, would you like me to upload sample data here or in the modelling discussion? The modelling discussion is locked to collaborators only.

**Comment by edmondchuc** [comment]
Hi @miekeGR, were you able to create a [new ](https://github.com/ternaustralia/ontology_tern/discussions/new) discussion post and tag it with "Modelling"?

**Comment by miekeGR** [comment]
Yes, I believe so. Thanks Edmond. I hope the attachments work ok for you.
