### ISSUE TITLE
Separate Shapes from Ontology definitions

### ISSUE THREAD

**Issue by nicholascar** [ternaustralia/ontology_tern#56]
Currently the TERN Ontology uses a legitimate but restrictive form of Shapes declarations where the Shapes are bound to class definitions. E.g., for the class `tern:Sample`:

```turtle
tern:Sample
  a owl:Class ;
  a sh:NodeShape ;
  ...
  sh:property [
      a sh:PropertyShape ;
      sh:path sosa:isResultOf ;
      sh:class tern:Sampling ;
      sh:minCount 1 ;
      sh:name "is result of" ;
      sh:nodeKind sh:IRI ;
    ] ;
  sh:property [
      a sh:PropertyShape ;
      sh:path sosa:isSampleOf ;
      sh:class tern:FeatureOfInterest ;
      sh:minCount 1 ;
      sh:name "is sample of" ;
      sh:nodeKind sh:IRI ;
    ] ;
.
```

This pattern, while technically OK in RDF, makes it hard to identify individual requirements because the Shapes aren't distinct from the ontology items, e.g. Class. So a Requirement for the BDR taken from this Shape but articulated in English, such as "All Samples must be the result of exactly one Sampling, indicated with a `sosa:isResultOf` property", can't be IDed. Again, not an issue in execution of the RDF but a pain for Requirements listing in Specification documents, test cases and so on.

A better pattern would be this:

```turtle
tern:Sample
  a owl:Class ;
  ...
.

tern:SampleShape
  a sh:NodeShape ;
  sh:property
    tern:SampleIsResultOfShape ,
    tern:SampleIsSampleOfShape ;
.

tern:SampleIsResultOfShape
      a sh:PropertyShape ;
      sh:path sosa:isResultOf ;
      sh:class tern:Sampling ;
      sh:minCount 1 ;
      sh:name "is result of" ;
      sh:nodeKind sh:IRI ;
.

tern:SampleIsSampleOfShape
      a sh:PropertyShape ;
      sh:path sosa:isSampleOf ;
      sh:class tern:FeatureOfInterest ;
      sh:minCount 1 ;
      sh:name "is sample of" ;
      sh:nodeKind sh:IRI ;
.
```

With this form, I can indicate specific Shapes by their unique IRIs.

Also we - BDR builders - have a strong preference for separating ontology from Shapes. This is due to the way our BDR application layer (SURROUND Ontology Platform) manages different assets, so, if the above split can be implemented, could the Shapes all be in a separate file to the ontology, perhaps:

* tern.ttl - ontology
* tern.shapes.ttl - shapes

You can, of course, combine them for your tooling (e.g. the documentation tool used for https://linkeddata-dev.tern.org.au/tern-ontology).

This linked Shape/ontology patterning also prevents the reuse of Property Shapes, e.g. `Observation`, `SiteVisit` and `FeatureOfInterest` all have the following Shape:

```turtle
  sh:property [
      a sh:PropertyShape ;
      sh:path <http://rdfs.org/ns/void#inDataset> ;
      sh:class tern:RDFDataset ;
      sh:maxCount 1 ;
      sh:minCount 1 ;
      sh:nodeKind sh:IRI ;
    ] ;
```

But this is re-articulated 3 time because, in current form, it can't be reused.

**Comment by edmondchuc** [comment]
Resolved by https://github.com/ternaustralia/ontology_tern/pull/91.

**Comment by edmondchuc** [comment]
New issue for reuse of property shapes via named nodes, see https://github.com/ternaustralia/ontology_tern/issues/106.
