### ISSUE TITLE
Violation of time:Instant + time:inXSDDateTimeStamp ontology requirements

### ISSUE THREAD

**Issue by nicholascar** [ternaustralia/ontology_tern#57]
The `tern:Instant` class is declared a subclass of `time:Instant` but the attached Shapes allow for values which violate `time:Instant` requirements.

`time:inXSDDateTimeStamp` has a range value of `xsd:dateTimeStamp` and yet the TERN ontology, when requiring use of this property for class `tern:Instant` allows for `xsd:dateTimeStamp` & `xsd:dateTime`:

```turtle
tern:Instant
  a owl:Class ;
  a sh:NodeShape ;
  rdfs:label "Instant" ;
  rdfs:subClassOf time:Instant ;
  sh:property [
      a sh:PropertyShape ;
      sh:path time:inXSDDateTimeStamp ;
      sh:maxCount 1 ;
      sh:minCount 1 ;
      sh:name "in XSDDate time stamp" ;
      sh:or (
          [ sh:datatype xsd:dateTimeStamp ; ]
          [ sh:datatype xsd:dateTime ; ]
        ) ;
    ] ;
.
```

I'm pretty sure `<x> time:inXSDDateTimeStamp "y"^^xsd:dateTime` will fail in some validators derived from OWL TIME.

**Comment by edmondchuc** [comment]
I originally wanted to use [time:inXSDDateTime](https://www.w3.org/TR/owl-time/#time:inXSDDateTime) which has a range value of `xsd:dateTime` but it is now deprecated. 

The docs also adds a note:
> The property :inXSDDateTime is replaced by :inXSDDateTimeStamp which makes the time-zone field mandatory.

In short, I think you're right and the `sh:datatype` must only be `xsd:dateTimeStamp` where the time-zone is made explicit. 

Although this change may not be required if we remove the use of `Instant` all together in favour of literal values as you have mentioned in https://github.com/ternaustralia/ontology_tern/issues/58.

**Comment by nicholascar** [comment]
> Although this change may not be required...

I think you should only require a `time:Instant` if case can be made for temporality expressed in ways other than date/dateTime values. Fancy `Instant` values are really only useful if a. You want to temporally relate them to other things; b. You want to use non-Gregorian time like Millions of Years Ago etc. Otherwise yes, I think a simple literal value for `sosa:phenomenonTime` will do.

**Comment by dr-shorthair** [comment]
In `sosa` it is an `owl:ObjectProperty`

**Comment by edmondchuc** [comment]
My proposal in https://github.com/ternaustralia/ontology_tern/issues/58#issuecomment-986461402. To be consistent with `sosa`, we should not use a literal value for `sosa:phenomenonTime`.

**Comment by nicholascar** [comment]
Oh yes, of course! So I'm not sure what to do here, perhaps some sort of wording, in the Shape message perhaps, that this is only expected to be a dateTime(Stamp) via an Instant.

**Comment by nicholascar** [comment]
I think your comment in #58 is the best approach.

**Comment by edmondchuc** [comment]
One of my tasks now is to add `sh:description` to each of the property constraints of a class hoping to make things clearer.

**Comment by nicholascar** [comment]
In the best case, these new `sh:description` properties would be on stand-alone Node/Property Shapes, as per the suggestion in #56
