### ISSUE TITLE
Inconsistency of RDFDataset definition

### ISSUE THREAD

**Issue by nicholascar** [ternaustralia/ontology_tern#60]
The `tern:RDFDataset` class is defined as:

_??_ -- no definition given in the ontology!

Inferring its definition from `void:Dataset` and `dcat:Distribution` that it is a subclass of:

* VoID `Dataset`: "A set of RDF triples that are published, maintained or aggregated by a single provider."
* DCAT `Distribution`: "A specific representation of a dataset. A dataset might be available in multiple serializations that may differ in various ways, including natural language, media-type or format, schematic organization, temporal and spatial resolution, level of detail or profiles (which might specify any or all of the above)."

So we have something like:

> A specific representation of a dataset that is a set of RDF triples that are published, maintained or aggregated by a single provider...

But now we have a problem as we can't both conform to VoID's "A set of RDF triples" and DCAT's "...multiple serializations that may differ in various ways, including natural language, media-type or format...". Even if we allowed only RDF formats, what about "A dataset might be available in ... [different forms of] ... temporal and spatial resolution, level of detail or profiles"? 

Clearly we have a conflation of a conceptual package of information (VoID Dataset) and a resource (DCAT Distribution). Even though VoID's Dataset is RDF-locked, it's still not the same as a DCAT Distribution.

**Comment by smguru** [comment]
@nicholascar noted, probably @edmondchuc will update the model with definition.

**Comment by edmondchuc** [comment]
@nicholascar I see your point. For now, I will remove `rdfs:subClassOf dcat:Distribution`. 

Related discussions: https://github.com/ternaustralia/ontology_tern/discussions/84#discussioncomment-2078809

**Comment by dr-shorthair** [comment]
I fear these arguments are heading into tetrapyloctemy. I don't quite see the conflict that @nicholascar describes, but OTOH I don't think VoID is used much, or DCAT either outside of Europe, so these sub-classing relationships aren't very important anyway. `tern:RDFDataset` is clear enough. Links to niche external vocabs are neither here nor there in practice.
