### ISSUE TITLE
Inconsistency with PROV for wasAssociatedWith use

### ISSUE THREAD

**Issue by nicholascar** [ternaustralia/ontology_tern#61]
A `tern:Observation` _may_ have a property `prov:wasAssociatedWith` which, according to TERN Shapes, may indicate a `sh:IRIOrLiteral` but PROV-O does not allow for literal use. From PROV:

```turtle
:wasAssociatedWith
    ...
    rdfs:domain :Activity ;
    ...
    rdfs:range :Agent ;
    rdfs:subPropertyOf :wasInfluencedBy ;
    owl:propertyChainAxiom (:qualifiedAssociation :agent) ;
    ...
.
```

So you need to either restrict your Shape or invent a looser property.

**Comment by smguru** [comment]
@nicholascar we will update the shape constraints
