### ISSUE TITLE
Site geometry

### ISSUE THREAD

**Issue by dr-shorthair** [ternaustralia/ontology_tern#67]
For many sites there is only a point location. 
The definition of `tern:Site` should allow this directly. 

I suggest just using `geo:hasGeometry` in the OWL/RDFS, and then add an OR SHACL rule to constrain it to a Point or Polygon.

**Comment by nicholascar** [comment]
Why would you constrain the geometries with SHACL? Don't you just want to say that a Site must have a `geo:hasGeometry` and leave it at that? That way, it can be a polygon or a point or whatever, but you don't need to look into the particular geometry type.

**Comment by dr-shorthair** [comment]
Agreed. Not sure of the utility of `tern:polygon`.

**Comment by smguru** [comment]
agree with that geometry can polygon, point, line just like geometry class in postGIS :)

**Comment by edmondchuc** [comment]
Removed `tern:polygon` on `Site` in https://github.com/ternaustralia/ontology_tern/pull/100.
