### ISSUE TITLE
What is the purpose of Sample geometry?

### ISSUE THREAD

**Issue by nicholascar** [ternaustralia/ontology_tern#69]
Since a Sampling has a geometry - where it was done - we can infer that that's where a Sample comes from. What then is the value in recording a location for the Sample? Additionally, I think it misleading to record Sample location as the sample may actually change its place (i.e. when I take it back to the lab). 

I think best to _require_ location for the Sampling (as discussed: either directly with geometry or indirectly via links to a Site or indirectly via other spatial relations to a Feature) and to infer initial location for a Sample from that and to either discourage, or best prevent, location for a Sample. directly.

**Comment by dr-shorthair** [comment]
An **act of Sampling** does not have a geometry itself. It has a **Feature of Interest**, just like an **Observation** (and an Actuation) does. 
The Feature of Interest often has a location or geometry. The location or geometry of this Feature of Interest is likely to be the scientifically-interesting location or geometry for the **Sample**. So yes, I agree that it is the location of where it came from that is important, though the way this is modeled is not quite how you describe. 

Mind you, a **Site** does have a location and geometry. And some Sites can also be thought of as Samples: for example, an Ecological Observation Site is usually positioned to be 'representative' of a tract or an ecosystem, for example. So the subset of Samples called 'Sites' (the Monitoring- and Observation-sites, anyway) probably do have an intrinsic geometry.

**Comment by dr-shorthair** [comment]
So I guess the proposal is to remove `geo:hasGeometry` from the expected properties of `tern:Sample`.

**Comment by edmondchuc** [comment]
Some survey protocols establish sites (`tern:Site`) where the site is further divided into quadrats or transects (`tern:Sample`).  These quadrats or transects sometimes have a geometry and they relate to the `tern:Site` via `sosa:isSampleOf`. Please see this [page](https://ternaus.atlassian.net/wiki/spaces/DAWE/pages/2217771011/Modelling+sites+transects+and+quadrats) for more information (yet to be migrated to the new site). 

Different types of features (samples) are represented through the use of `tern:featureType`. It can be a quadrat, transect, plant individual, plant occurrence, animal occurrence, etc.

`tern:Sample` only defines the requirement of at least 1 value for both `sosa:isResultOf` and `sosa:isSampleOf`. It has access to `geo:hasGeometry` through its superclass `tern:FeatureOfInterest`.

`tern:Sample`: https://w3id.org/tern/ontologies/tern/Sample

**Comment by nicholascar** [comment]
OK, well then if the expectation is that `Sample` will usually only have a geometry by inheritance, i.e. by being an `FoI`, then I think that works well. 

This again highlights a need to split Shapes from ontology, as per Issue #56, so that while ontological any old `Site` can have a geometry, the shapes, at least for NDES or BDR, will only be looking for them for special `Sample` types, such as `Site`, or for pure `Sample` and other kinds like `MaterialSample` looking for not them (Exactly 0).

**Comment by edmondchuc** [comment]
Ontology and SHACL are now separated as per https://github.com/ternaustralia/ontology_tern/pull/91.
