### ISSUE TITLE
Relationship of Attribute to ObservableProperty

### ISSUE THREAD

**Issue by dr-shorthair** [ternaustralia/ontology_tern#7]
TERN Ontology includes the class `Attribute` ('key-value pair' according to the documentation). 
Unclear if/how this relates to `sosa:ObservableProperty`.

**Comment by edmondchuc** [comment]
The class `Attribute` is equivalent to the class `ssn:Property`. This needs to be documented and explained further. Other related properties:
- `tern:hasAttribute` -> `ssn:hasProperty`
- `tern:isAttributeOf` -> `son:isPropertyOf`

To be honest, I totally forgot SSN had `ssn:Property` and it only occurred to me last week. 

We currently use the `Attribute` class to capture additional facts in different scenarios that are not observations.

1. We use the `Attribute` class to capture information within the context of an observation. For example, in CORVEG the geological observations have information about the reliability (high, medium, low) of the results. 
2. We use the `Attribute` class to capture information about individuals. This can be applied to any of the classes such as `Sampling` or `Instrument`. For example, the size of the soil ring (10 cm) used to collect the soil sample is recorded by the `Attribute` class on the `Instrument`. Another example is capturing observations of the basal hits count through the use of a basal wedge. The basal wedge factor is captured as an `Attribute` of the `Instrument` (basal wedge).
3. Originally, we modelled only things that were observed in the field as observations and things that were observed outside the context of the site visit were modelled as attributes. An example of this is the determined species name. In O&M, this makes sense to be modelled as an observation. We were thinking to have observation types to illustrate if an observation was a field observation, derived observation, etc. 

Though this `Attribute` or `ssn:Property` class is necessary to capture additional information in different scenarios, we are concerned that it is making the model too complicated for users to submit data that conforms to the standard. 

@smguru's suggestion is to make everything an `ObservableProperty` but see points 1 and 2. 

On a separate but related note, we would like to model the cardinality of attributes and observable properties based on the `featureType` value (plant individual, landform, plant community, etc.) without using OWL. Note the attributes and observable properties are modelled as SKOS controlled vocabularies. We want to keep the core model small and domain-agnostic but we also want to somehow express what attributes and observable properties a certain feature type must/may have. For example, every plant individual may have a determined species name.

**Comment by dr-shorthair** [comment]
Thanks @edmondchuc. I had inferred that was the intention (i.e. to "use the Attribute class to capture additional facts in different scenarios that are not observations"). Good. 

But as you note, there should be a relationship of `Attribute` to `ssn:Property`, at least. As you can see, `sosa:ObservableProperty` is a sub-class, being the properties whose values are subject to determination by an act of observation. The corollary is that properties whose values are determined some other way are members of the super-class. 

The key point about Observations is that they result in an _estimate_ of the true value, with uncertainties or systematic errors due to the procedure and observer (sensor) that is used. If the uncertainty is of no interest, then there is no point in modeling it as an act of observation and recording all the observation properties.

**Comment by edmondchuc** [comment]
`tern:Attribute` is now a subclass of `ssn:Property` to align with `sosa`.
