### ISSUE TITLE
Rename tern:dimension to tern:dimensions

### ISSUE THREAD

**Issue by nicholascar** [ternaustralia/ontology_tern#79]
`tern:dimension` should be better names "dimensions" as you clearly want more than one (e.g. the example of 100x100)

Also, the definition contains a mispelling.

Also, consider providing guidance for the use of GeoSPARQL 1.1's [geo:hasArea](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_property_geohasarea) property somewhere.

**Comment by dr-shorthair** [comment]
Or is it `extent` ?

**Comment by nicholascar** [comment]
Could be `extent`: definitely needs clarity though! But I think `dimensions` or `dimentionsLengths` would be better as, from the example at least, this property gives shape information (length x breadth), not just a lumped extent value.

**Comment by edmondchuc** [comment]
Related https://github.com/ternaustralia/ontology_tern/issues/13

**Comment by nicholascar** [comment]
@edmondchuc closing this one as a duplicate
