### ISSUE TITLE
Is SiteVisit required for things like subplots, quadrats and transects?

### ISSUE THREAD

**Issue by edmondchuc** [ternaustralia/ontology_tern#8]
Currently, subplots, quadrats and transects of a sampling site are modelled as `tern:Site`. They are represented using `dcterms:isPartOf` and `dcterms:hasPart`. 

Observations made within a `tern:Site` usually expect a relationship to a `tern:SiteVisit`. It is quite verbose to also have to declare these for the subplots, quadrats and transects within a main sampling site.

In these situations, should we create rules to ensure that if an activity (observation, sampling) has a relationship to a `tern:Site` then they should also have a relationship to a `tern:SiteVisit`. And the `tern:SiteVisit` must link to the top-level `tern:Site`.

**Comment by dr-shorthair** [comment]
It may be that the relationship of the Site class to classes for site-component sub-plots, quadrats, transects is not `subClassOf`. 
If they do not have all the properties of `Site` then they are not sub-classes. 

This modeling confusion often arises in conjunction with part-whole relationships. 
At an _individual_ level the components 'inherit' some properties from the 'parent', but at the _class_ level they do not.

**Comment by edmondchuc** [comment]
In the latest meeting with the team, it was concluded that it is appropriate to have `SiteVisit` for each `Site` in a nested site. This supports the use case where some sites are broken up into multiple levels of subsites and each subsite may be visited on different days or at different times. 

Observations and samplings must ensure they point to the proximate site and site visit. 

An example of this in diagram form:
![nested-sites.png](https://i.imgur.com/nALoQ3h.png)

The properties `dcterms:hasPart` and `dcterms:isPartOf` has been added to `tern:SiteVisit` class in the `develop` branch. 

Discussions should be made as to whether we require properties such as `tern:ultimateSite` and `tern:ultimateSiteVisit` to point to the ultimate `Site` and `SiteVisit` of a survey. See also the similar pattern described in [ssn-ext](https://www.w3.org/TR/2020/WD-vocab-ssn-ext-20200116/#sosa:hasUltimateFeatureOfInterest).

**Comment by edmondchuc** [comment]
Nested sites and nested site visits have been dropped from the information model. It introduces too much complexity at this point. It is better to utilise a mixin pattern like the new ManagedFeature class to record additional management metadata about things like sites, transects, quadrats and subplots. Site Visit still exists for Sites (ultimate feature of interest). 

See also https://github.com/ternaustralia/ontology_tern/pull/23
