### ISSUE TITLE
errors when importing TERN ontology into Protege / Graph DB

### ISSUE THREAD

**Issue by gwittich** [ternaustralia/ontology_tern#80]
These errors have occurred in the Protege and Graph DB. We're wondering if this is an issue with the ontology as the same or similar issues are turning up in these tools.
![Screen Shot 2022-01-12 at 10 28 41 am](https://user-images.githubusercontent.com/62985375/149071496-eb666c02-315e-4b9b-9f8b-3182b433167d.png)

**Comment by edmondchuc** [comment]
Hi @gwittich, I'm not sure if it's within the scope of this issue tracker to debug errors in Protege. I can try and help, but I can't do much unless you provide some error messages or logs provided by Protege.

Are you able to provide some error messages or logs on GraphDB failing to import? It wouldn't raise any errors during imports unless there is a syntax error in the RDF serialisation. At TERN, we have systems set up to automatically import new versions of the TERN Ontology into our GraphDB for a long time now. Unless you can provide some error logs on what the import errors are in GraphDB, this issue will be tagged as `wontfix` and will be closed by next week.

**Comment by gwittich** [comment]
In trying to be brief in the title I have been misleading. Sorry.
The issue is that after importing TERN.ttl into any of several tools many of the S&P's are displayed as 'ErrorNN', seemingly unable to display the 'SubClassOf' information.

**Comment by dr-shorthair** [comment]
Protege works on strict OWL-DL ontologies. 
It throws errors for various reasons if the ontologies are not strict OWL-DL. 
For example, cardinality constraints are outside of OWL-DL. 
Protege is primarily for ontologies that support reasoning, rather than datasets (graphs) that can be queried using SPARQL. 

And Protege does not support SHACL (last time I looked). 

Protege is the wrong tool for our application.

**Comment by edmondchuc** [comment]
@gwittich I'd recommend using TopBraid Composer instead of Protege. There is a free version available which you can use to see the class hierarchy.

You can also view the TERN Ontology's classes at https://linkeddata.tern.org.au/viewers/tern-ontology.
