### ISSUE TITLE
complete list of Cs & Ps (TERN Ontology and imported / reference ontologies)

### ISSUE THREAD

**Issue by gwittich** [ternaustralia/ontology_tern#81]
Can TERN please provide a complete list of all the ABIS-defined Classes & Properties (TERN Ontology and Messages stuff) AND other terms expected for use (from imported / reference ontologies) in converting DwC? (issue generating these ourselves as per Issue 80.)

**Comment by edmondchuc** [comment]
Please see https://linkeddata.tern.org.au/viewers/tern-ontology. 

Also note that there is a PR https://github.com/ternaustralia/ontology_tern/pull/55 which will refactor the specialised classes of `tern:Value` and align the TERN Ontology more with SSN.

TERN Ontology only deals with the domain-specific details and does not include the BDR messaging system by Surround [1].

>  ABIS-defined Classes & Properties ... in converting DwC

Once there's some consensus with https://github.com/ternaustralia/ontology_tern/discussions/53, the details of converting Darwin Core data into the TERN Ontology will be documented in the cookbook.

[1] https://github.com/surroundaustralia/abis

**Comment by gwittich** [comment]
You are quite correct and fairly state that you can't be expected to respond to matter relating to Surround Messaging - (poorly worded request).

A better request would have been:
"Can TERN please provide a complete list of all the ABIS-defined Classes & Properties available within  TERN Ontology from the Tern Ontology and AND other terms expected for use (from imported / reference ontologies). (issue generating these ourselves as per Issue 80.)"




(I possibly should have posted this in the Discussions section - oops)

**Comment by edmondchuc** [comment]
As mentioned in https://github.com/ternaustralia/ontology_tern/issues/80, please try TopBraid Composer. 

You can use TopBraid Composer to open any RDF file (including the TERN Ontology) and view the instance data or the class/property hierarchy list. It will also handle imports stated by `owl:imports`. You can use this to view the imported classes and properties.

**Comment by dr-shorthair** [comment]
There is a 'Free Edition' of TBC available here https://www.topquadrant.com/topbraid-composer-install/ 
Note that it is version 6, and does not include the diagramming. 

A license for the full version ('Maestro Edition') is a significant investment, but I find it is worth it.
